version: '3.9'

services:
  db:
    ports:
     - "5432:5432"
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
        dockerfile: .docker/Dockerfile
        context: .
    command: "python manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/var/app/
