# Generated by Django 4.2.1 on 2023-05-17 08:23

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import read_club.models.book


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=260)),
                ('preview', models.FileField(max_length=25, upload_to='preview')),
                ('author', models.CharField(max_length=120)),
                ('published', models.IntegerField(default=2023, validators=[django.core.validators.MinValueValidator(1990), read_club.models.book.max_value_current_year])),
                ('publisher', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='read_club.book')),
                ('start', models.DateField(default=datetime.date.today)),
                ('finish', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='read_club.event')),
            ],
        ),
    ]
