# Generated by Django 4.2.1 on 2023-05-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='read_club.book'),
        ),
        migrations.AlterField(
            model_name='note',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='read_club.event'),
        ),
    ]
